"""prayer network

Revision ID: 1f984ada7955
Revises: 30dec66b204d
Create Date: 2026-07-02 03:15:07.418423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f984ada7955'
down_revision: Union[str, Sequence[str], None] = '30dec66b204d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prayer_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('prayed_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prayer_id'], ['prayers.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prayer_id', 'recipient_user_id', name='uq_prayer_recipient_user')
    )
    op.create_index(op.f('ix_prayer_recipients_created_at'), 'prayer_recipients', ['created_at'], unique=False)
    op.create_index(op.f('ix_prayer_recipients_id'), 'prayer_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_recipients_prayer_id'), 'prayer_recipients', ['prayer_id'], unique=False)
    op.create_index(op.f('ix_prayer_recipients_recipient_role'), 'prayer_recipients', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_prayer_recipients_recipient_user_id'), 'prayer_recipients', ['recipient_user_id'], unique=False)
    op.add_column('prayers', sa.Column('visibility', sa.String(), nullable=True))
    op.execute("""
    UPDATE prayers
    SET visibility = COALESCE(visibility, 'community')
""")
    op.create_index(op.f('ix_prayers_visibility'), 'prayers', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prayers_visibility'), table_name='prayers')
    op.drop_column('prayers', 'visibility')
    op.drop_index(op.f('ix_prayer_recipients_recipient_user_id'), table_name='prayer_recipients')
    op.drop_index(op.f('ix_prayer_recipients_recipient_role'), table_name='prayer_recipients')
    op.drop_index(op.f('ix_prayer_recipients_prayer_id'), table_name='prayer_recipients')
    op.drop_index(op.f('ix_prayer_recipients_id'), table_name='prayer_recipients')
    op.drop_index(op.f('ix_prayer_recipients_created_at'), table_name='prayer_recipients')
    op.drop_table('prayer_recipients')
    # ### end Alembic commands ###
