"""add public pastor profile setting

Revision ID: 27cf1b151ccf
Revises: b470eea6ec7f
Create Date: 2026-07-07 05:26:21.957603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cf1b151ccf'
down_revision: Union[str, Sequence[str], None] = 'b470eea6ec7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastor_profiles', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastor_profiles', 'is_public')
    # ### end Alembic commands ###
