"""add pastor profile visibility

Revision ID: 283725dde09f
Revises: 27cf1b151ccf
Create Date: 2026-07-07 06:10:51.683818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283725dde09f'
down_revision: Union[str, Sequence[str], None] = '27cf1b151ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "pastor_profiles",
        sa.Column(
            "visibility",
            sa.String(length=20),
            nullable=False,
            server_default="public"
        )
    )

    # Optional: remove the server default after existing rows are populated.
    op.alter_column(
        "pastor_profiles",
        "visibility",
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastor_profiles', 'visibility')
    # ### end Alembic commands ###
