"""upgrade pastor profiles

Revision ID: b470eea6ec7f
Revises: 1f984ada7955
Create Date: 2026-07-04 15:06:21.621818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b470eea6ec7f'
down_revision: Union[str, Sequence[str], None] = '1f984ada7955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastor_profiles', sa.Column('mission_statement', sa.Text(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('church_logo', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('church_size', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('specialties', sa.Text(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('denomination', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('years_in_ministry', sa.Integer(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('ordination_year', sa.Integer(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('state', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('time_zone', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('email_public', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('favorite_scripture', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('service_times', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('accepts_prayer_requests', sa.Boolean(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('allow_direct_messages', sa.Boolean(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('pastor_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_pastor_profiles_slug'), 'pastor_profiles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pastor_profiles_slug'), table_name='pastor_profiles')
    op.drop_column('pastor_profiles', 'updated_at')
    op.drop_column('pastor_profiles', 'slug')
    op.drop_column('pastor_profiles', 'is_verified')
    op.drop_column('pastor_profiles', 'allow_direct_messages')
    op.drop_column('pastor_profiles', 'accepts_prayer_requests')
    op.drop_column('pastor_profiles', 'service_times')
    op.drop_column('pastor_profiles', 'languages')
    op.drop_column('pastor_profiles', 'favorite_scripture')
    op.drop_column('pastor_profiles', 'twitter')
    op.drop_column('pastor_profiles', 'instagram')
    op.drop_column('pastor_profiles', 'youtube')
    op.drop_column('pastor_profiles', 'facebook')
    op.drop_column('pastor_profiles', 'email_public')
    op.drop_column('pastor_profiles', 'phone')
    op.drop_column('pastor_profiles', 'time_zone')
    op.drop_column('pastor_profiles', 'country')
    op.drop_column('pastor_profiles', 'state')
    op.drop_column('pastor_profiles', 'city')
    op.drop_column('pastor_profiles', 'ordination_year')
    op.drop_column('pastor_profiles', 'years_in_ministry')
    op.drop_column('pastor_profiles', 'denomination')
    op.drop_column('pastor_profiles', 'specialties')
    op.drop_column('pastor_profiles', 'church_size')
    op.drop_column('pastor_profiles', 'church_logo')
    op.drop_column('pastor_profiles', 'mission_statement')
    # ### end Alembic commands ###
