"""add sermon updated_at

Revision ID: f0f6db5f03db
Revises: 7fd1bc5adbd2
Create Date: 2026-06-20 10:01:49.414141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0f6db5f03db'
down_revision: Union[str, Sequence[str], None] = '7fd1bc5adbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pastors_email'), 'pastors', ['email'], unique=True)
    op.create_index(op.f('ix_pastors_id'), 'pastors', ['id'], unique=False)
    op.drop_table('notifications')
    op.drop_table('prayer_reactions')
    op.alter_column('prayers', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_prayers_created_at'), 'prayers', ['created_at'], unique=False)
    op.create_index(op.f('ix_prayers_id'), 'prayers', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sermon_comments_created_at'), 'sermon_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_sermon_comments_pastor_id'), 'sermon_comments', ['pastor_id'], unique=False)
    op.create_index(op.f('ix_sermon_comments_sermon_id'), 'sermon_comments', ['sermon_id'], unique=False)
    op.create_foreign_key(None, 'sermon_comments', 'sermons', ['sermon_id'], ['id'])
    op.create_foreign_key(None, 'sermon_comments', 'users', ['pastor_id'], ['id'])
    op.add_column('sermons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('sermons', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sermons_created_at'), 'sermons', ['created_at'], unique=False)
    op.create_index(op.f('ix_shared_sermons_created_at'), 'shared_sermons', ['created_at'], unique=False)
    op.create_index(op.f('ix_shared_sermons_from_pastor_id'), 'shared_sermons', ['from_pastor_id'], unique=False)
    op.create_index(op.f('ix_shared_sermons_sermon_id'), 'shared_sermons', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_shared_sermons_to_pastor_id'), 'shared_sermons', ['to_pastor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_sermons_to_pastor_id'), table_name='shared_sermons')
    op.drop_index(op.f('ix_shared_sermons_sermon_id'), table_name='shared_sermons')
    op.drop_index(op.f('ix_shared_sermons_from_pastor_id'), table_name='shared_sermons')
    op.drop_index(op.f('ix_shared_sermons_created_at'), table_name='shared_sermons')
    op.drop_index(op.f('ix_sermons_created_at'), table_name='sermons')
    op.alter_column('sermons', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sermons', 'updated_at')
    op.drop_constraint(None, 'sermon_comments', type_='foreignkey')
    op.drop_constraint(None, 'sermon_comments', type_='foreignkey')
    op.drop_index(op.f('ix_sermon_comments_sermon_id'), table_name='sermon_comments')
    op.drop_index(op.f('ix_sermon_comments_pastor_id'), table_name='sermon_comments')
    op.drop_index(op.f('ix_sermon_comments_created_at'), table_name='sermon_comments')
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_prayers_id'), table_name='prayers')
    op.drop_index(op.f('ix_prayers_created_at'), table_name='prayers')
    op.alter_column('prayers', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('prayer_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prayer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prayer_reactions_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.drop_index(op.f('ix_pastors_id'), table_name='pastors')
    op.drop_index(op.f('ix_pastors_email'), table_name='pastors')
    op.drop_table('pastors')
    # ### end Alembic commands ###
