"""
Provider-independent ministry skill contracts for Xyniva.

Skills produce ministry content. They are intentionally separate from
conversation actions, which propose product mutations such as saving,
updating, or deleting a sermon.
"""

from __future__ import annotations

from typing import Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
)


MinistrySkillName = Literal[
    "sermon.generate",
    "sermon.refine",
    "biblical.research",
]


class SermonPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(min_length=1, max_length=240)
    content: str = Field(min_length=1)


class SermonGenerateInput(BaseModel):
    """
    Structured input for Sermon Studio generation.

    Defaults intentionally preserve the existing XynaFaith sermon
    request contract so V2 can evolve without breaking V1 clients.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    input: str = ""
    scripture: str = ""
    denomination: str = "general"
    audience: str = ""
    context: str = ""
    tone: str = "balanced"
    duration: str = "30"

    @model_validator(mode="after")
    def require_topic_or_scripture(self):
        if not self.input and not self.scripture:
            raise ValueError(
                "A sermon topic or scripture is required"
            )

        return self


class SermonOutput(BaseModel):
    """
    Canonical structured sermon generated by XynAssist.

    This matches the stable public sermon shape currently consumed by
    XynaFaith while giving XynAssist its own provider-independent
    contract.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(min_length=1)
    scripture: str = ""
    introduction: str = Field(min_length=1)
    main_points: list[SermonPoint] = Field(min_length=1)
    application: str = Field(min_length=1)
    conclusion: str = Field(min_length=1)


class SermonRefineInput(BaseModel):
    """
    Refine an existing sermon without mutating XynaFaith storage.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    sermon: SermonOutput
    instruction: str = Field(min_length=1, max_length=2000)
    denomination: str = "general"
    audience: str = ""
    context: str = ""
    tone: str = "balanced"


class BiblicalResearchInput(BaseModel):
    """
    Request biblical research for a passage, topic, or both.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    scripture: str = ""
    topic: str = ""
    question: str = ""
    denomination: str = "general"
    audience: str = ""
    context: str = ""

    @model_validator(mode="after")
    def require_research_subject(self):
        if not self.scripture and not self.topic:
            raise ValueError(
                "A scripture passage or research topic is required"
            )

        return self


class BiblicalResearchSection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    heading: str = Field(min_length=1, max_length=240)
    content: str = Field(min_length=1)


class BiblicalResearchOutput(BaseModel):
    """
    Structured research result.

    The contract deliberately distinguishes textual observations,
    interpretive synthesis, theological differences, and ministry
    application rather than presenting interpretation as biblical text.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(min_length=1)
    scripture: str = ""
    summary: str = Field(min_length=1)

    observations: list[BiblicalResearchSection] = Field(
        default_factory=list
    )
    interpretation: list[BiblicalResearchSection] = Field(
        default_factory=list
    )
    theological_perspectives: list[
        BiblicalResearchSection
    ] = Field(default_factory=list)
    ministry_application: list[
        BiblicalResearchSection
    ] = Field(default_factory=list)

    cautions: list[str] = Field(default_factory=list)

    @field_validator("cautions")
    @classmethod
    def reject_blank_cautions(
        cls,
        value: list[str],
    ) -> list[str]:
        normalized = []

        for item in value:
            item = item.strip()

            if not item:
                raise ValueError(
                    "Research cautions cannot be blank"
                )

            normalized.append(item)

        return normalized


MINISTRY_SKILLS: frozenset[str] = frozenset(
    {
        "sermon.generate",
        "sermon.refine",
        "biblical.research",
    }
)


def is_ministry_skill(value: str) -> bool:
    return value in MINISTRY_SKILLS
